datasources:
  default:
    url: jdbc:h2:file:/data/db/soundboard;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:h2:file:////data/db/soundboard;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''

sound.folder: /data/sounds
token.secret: ${SOUNDBOARD_BOT_TOKEN_SECRET}
discord.token: ${SOUNDBOARD_BOT_DISCORD_TOKEN}
ffmpeg-base-path: /usr/bin
yt-dlp-base-path: /usr/bin