datasources:
  default:
    url: jdbc:h2:file:${SOUNDBOARD_BOT_SOUND_FOLDER}/testdb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

r2dbc:
  datasources:
    default:
      dialect: H2
      url: r2dbc:h2:file:///${SOUNDBOARD_BOT_SOUND_FOLDER}/testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''

token.secret: ${SOUNDBOARD_BOT_TOKEN_SECRET}
sound.folder: ${SOUNDBOARD_BOT_SOUND_FOLDER}
discord.token: ${SOUNDBOARD_BOT_DISCORD_TOKEN}
ffmpeg-base-path: ${SOUNDBOARD_BOT_FFMPEG_BASE_PATH}
yt-dlp-base-path: ${SOUNDBOARD_BOT_YT_DLP_BASE_PATH}

micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

auto-join: true

