name: Build and Push Docker Image
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assemble dockerfile

      - name: Docker login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd build/docker/main
          TAG_ID=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          docker build . \
            -t ghcr.io/bergdinkle/soundboard-bot:latest \
            -t ghcr.io/bergdinkle/soundboard-bot:${TAG_ID}
          docker push ghcr.io/bergdinkle/soundboard-bot:latest
          docker push ghcr.io/bergdinkle/soundboard-bot:${TAG_ID}